### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by ezekieldeleon** [leosac/leosac#123]
Hello everyone,

When I try to execute leosac I keep getting `illegal instruction`. Even if i pass `leosac -h` I get the same results.  I am using the latest stable release .deb which is 0.6.3. Anyone have the same issue and found a solution?

**Comment by Maxhy** [comment]
@ezekieldeleon which system are you running it from?

**Comment by Maxhy** [comment]
Fixed.
