### ISSUE TITLE
Example install guide is broken

### ISSUE THREAD

**Issue by Teslafly** [leosac/leosac#125]
The example install guide at https://leosac.github.io/leosac-doc/doc_output/develop/d5/d97/page_guide_rpi_piface_wiegand.html#install_guide
in the debian section, the command "apt-get install -f;" removes leosac, (maybe an update to apr-get?) wheres the intended purpose is to install missing dependencies.

I think it may be because the missing dependencies are not automatically installable.

```
The following packages have unmet dependencies:
 leosac : Depends: libboost-regex1.55.0 but it is not installable
          Depends: libboost-serialization1.55.0 but it is not installable
          Depends: libboost-serialization1.49.0 but it is not installable
          Depends: libtclap-dev but it is not installed
```

This is on a raspberry pi 3 with a brand new up to date raspbian installation.

**Comment by Maxhy** [comment]
Yeah that +/- outdated, please see https://github.com/leosac/leosac/blob/develop/doc/guides/guide_install_from_source.md instead.
