### ISSUE TITLE
SPI kernel Location

### ISSUE THREAD

**Issue by vanderpunk** [leosac/leosac#141]
For the "Installation Guide (part 1): Raspbian"
The location to turn on the SPI kernel has been moved to raspi-config --> Interface Options --> SPI.

![image](https://user-images.githubusercontent.com/69319211/187507384-c9da25ca-ab80-4663-81e6-69f5787a91a4.png)

**Comment by Maxhy** [comment]
Indeed, thanks for the report. Fixed, will be part of next documentation generation.
