### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Molini** [leosac/leosac#77]
Hi, Your wiki link is down and i just started using leosac and was confused how to setup the software side of things, like adding cards and the like.

**Comment by Liryna** [comment]
Hi @griggsy ,

Link was fixed 👍  https://github.com/leosac/leosac/wiki

**Comment by griggsy** [comment]
i can't seem to install leosac using the .deb file.

**Comment by griggsy** [comment]
My raspberry pi is stuck on committing changes when installing the .deb file
I can't seem to fix this issue

**Comment by griggsy** [comment]
<img width="1027" alt="error" src="https://cloud.githubusercontent.com/assets/14973848/22404896/2975ed20-e675-11e6-8234-dcff0dcd4d0a.png">
This is the error trying to run the command to install the dependencies.

**Comment by Liryna** [comment]
I think without `:` at the end it will work 👍

**Comment by xaqq** [comment]
Try running apt-get install --fix-missing then reinstall the .deb


This should pull the required and missing dependencies and allow you to
install.

**Comment by griggsy** [comment]
@xaqq i tried that command and tried reinstalling the deb and is says running and when i run the command listed on the install page it gets the same error as last time 
<img width="1024" alt="running" src="https://cloud.githubusercontent.com/assets/14973848/22416526/03f649c4-e70a-11e6-894f-91ab5e632b31.png">

**Comment by griggsy** [comment]
Fixed it, now just to figure out how to configure the modules as the wiki is confusing

**Comment by griggsy** [comment]
Think I have understood the modules bit. But how do I get it to load the auth File and config file, also how do I get the card Id to add the the auth file ?

**Comment by xaqq** [comment]
You have to specify them in the main configuration file. Have you followed [this](http://www.leosac.com/doc_output/develop/html/d5/d38/install_guide.html) guide ?

The complete configuration for this example is available [here](https://github.com/leosac/leosac/tree/develop/cfg/example/guide_rpi_piface_wiegand). Hopefully it is still valid.

You configure card ids in the auth file by manually writing XML. An you run the whole thing by typing `/path/to/leosac -k /path/to/config/file.xml`

**Comment by griggsy** [comment]
I mean is there a way to scan the card on my wiegand reader and see the card id to write into my auth file?

I understand how to add the modules into the config file. 😀

**Comment by griggsy** [comment]
I have tired that command but i get an error like this 
![error](https://cloud.githubusercontent.com/assets/14973848/22508266/2e56007c-e8c4-11e6-9908-6c91f8160239.jpeg)
This is my config 
it wont let me upload as xml so it is hosted on pastebin 
http://pastebin.com/LDJFkmay

**Comment by xaqq** [comment]
Hello, 
Your xml config file is not valid XML.
You're missing a few opening tag (didn't see `<modules>`) and some closing tag near the `doorman` module configuration.
