### ISSUE TITLE
Gui 

### ISSUE THREAD

**Issue by Molini** [leosac/leosac#82]
Could we possibly have a gui in the next update that we could use to configure the system ?

**Comment by xaqq** [comment]
Hello @griggsy, sorry there won't be a GUI in next release.
Maybe in the future though.

By the way, did you manage to fix your issue in #77 ?

**Comment by griggsy** [comment]
No I haven't been able to set up Leosac

Sent from my iPhone

On 7 Apr. 2017, at 05:15, KAPP Arnaud <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @griggsy<https://github.com/griggsy>, sorry there won't be a GUI in next release.
Maybe in the future though.

By the way, did you manage to fix your issue in #77<https://github.com/leosac/leosac/issues/77> ?

**Comment by Maxhy** [comment]
Started with https://github.com/leosac/leosac-web
