### ISSUE TITLE
Without PiFace

### ISSUE THREAD

**Issue by sercanbektas** [leosac/leosac#84]
Hi,
I already install leosac and try to run it on Raspberry Pi 3. I have a Wiegand reader. Is it possible to read 26 bit wiegand data without PiFace module? If yes can you share an example config file

**Comment by xaqq** [comment]
Hello,

Yes it is possible to do so.
You'll have to use the SYSFS_GPIO module.

Have a look at http://www.leosac.com/doc_output/develop/html/d2/d1b/mod_sysfsgpio_main.html for the documentation of SYSFS_GPIO.

You can have a look at https://github.com/leosac/leosac/blob/develop/cfg/dev-test/rpi-sysfs.xml too or the wiegand + piface tutorial and just use SYSFS_GPIO instead of PIFACEDIGITAL_GPIO.

**Comment by xaqq** [comment]
Hello,
Did you manage to configure how you like? Can I close this?

**Comment by sercanbektas** [comment]
Hello,
Thank you very much.Sorry for my late reply.Yes i can start program but i
cant see wiegand code which i swap to reader. Can you help me to show mu
wiegand  data on console. I want to learn my cards wiegand data and give
permission to that card. I have 37 bit card and nothing happens when i swap
card.
Best Regards
29 Haz 2017 Per, saat 11:37 tarihinde KAPP Arnaud <notifications@github.com>
şunu yazdı:

**Comment by xaqq** [comment]
Hello,

Can you show your config file?
Are you confident in your wiring of the pi and the reader?

**Comment by sercanbektas** [comment]
Hello,
Config file is what you sent me before and wiring photos is in attachments.
Thanks for your interest.That will be very helpfull for me. If i see that
card is read successfuly that is enough for me.
Best Regards

29 Haz 2017 Per, saat 21:41 tarihinde KAPP Arnaud <notifications@github.com>
şunu yazdı:

**Comment by xaqq** [comment]
Hello,

Attachment do not work :(

**Comment by sercanbektas** [comment]
Hello,
I attached again...sorry:(

1 Tem 2017 Cmt, saat 22:03 tarihinde KAPP Arnaud <notifications@github.com>
şunu yazdı:

**Comment by xaqq** [comment]
Hello,
What I meant was that sending attachment by email doesn't work at all on github.
They aren't attached to the issue. You have to upload them yourself and provide a link to them.

**Comment by sercanbektas** [comment]
![6d44f997-341b-46bb-bd14-5cd9cc17aa46](https://user-images.githubusercontent.com/18037901/27805225-3902310e-603c-11e7-940e-49343044d38b.jpg)
![47be631b-fca5-4232-bb1a-e231056bfe97](https://user-images.githubusercontent.com/18037901/27805228-3dafa0f6-603c-11e7-9d9a-1e521017e075.jpg)
![79776610-c2c5-49ce-a5af-a432ca62e8b8](https://user-images.githubusercontent.com/18037901/27805230-414ce9da-603c-11e7-853e-cd4ad4f0b4ba.jpg)
![d192d2dd-83e2-4f70-b642-23880e79f6b8](https://user-images.githubusercontent.com/18037901/27805234-44641d64-603c-11e7-8cd1-24f567c946d4.jpg)

**Comment by xaqq** [comment]
Hello,

So I'm not sure I understand correctly, but as far as I can tell your reader isnt powered, is it?
It seems you wired data0/data1 and the ground, but the reader seems to receive no power.

 What is the reference of your reader?

**Comment by Rokia88** [comment]
I am facing the same issue , have you managed to make it work without piface ?

**Comment by Maxhy** [comment]
I have updated the documentation on https://leosac.github.io/leosac-doc/doc_output/develop/ see https://leosac.github.io/leosac-doc/doc_output/develop/d2/d23/page_module_wiegand.html#mod_wiegand_wiring

For the record, Wiegand format decoding and advanced RFID features will be part of another Leosac update.

Closing this ticket then, feel free to comment for additional questions on that matter. Thanks.
