### ISSUE TITLE
Request: Add Zone to schedule/mapping

### ISSUE THREAD

**Issue by mqje** [leosac/leosac#87]
Can you please add the _src/core/auth/Zone_ to the **Schedule-mapping**. The **Door** is already a good feature, but we may need to add **Zone**. By that, I mean that a **Zone** can have a lot of **Door**, and if you put the **Zone** in the mapping, we could save a lot of time.

**Comment by Maxhy** [comment]
Done with 225b3f49f463870a0005e60faae3f98b2b12ee8a
